#!/usr/bin/env python3
"""
Convert rock tiles to MBTiles format for TileServer GL.
"""

import os
import sqlite3
from pathlib import Path
import argparse

def create_mbtiles(tiles_dir, output_file, name="Rock Tiles", description="DeepGIS Rock Imagery"):
    """
    Convert XYZ tile directory to MBTiles.
    
    Args:
        tiles_dir: Path to tiles (contains zoom/x/y.png structure)
        output_file: Output .mbtiles file
        name: Layer name
        description: Layer description
    """
    
    print(f"Creating MBTiles: {output_file}")
    print(f"Source: {tiles_dir}\n")
    
    # Create MBTiles database
    conn = sqlite3.connect(output_file)
    cursor = conn.cursor()
    
    # Create tables
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS metadata (
            name TEXT PRIMARY KEY,
            value TEXT
        )
    """)
    
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS tiles (
            zoom_level INTEGER,
            tile_column INTEGER,
            tile_row INTEGER,
            tile_data BLOB,
            PRIMARY KEY (zoom_level, tile_column, tile_row)
        )
    """)
    
    # Get bounds from tiles
    tiles_path = Path(tiles_dir)
    zoom_dirs = [z for z in tiles_path.iterdir() if z.is_dir() and z.name.isdigit()]
    
    if not zoom_dirs:
        print(f"Error: No zoom directories found in {tiles_dir}")
        return
    
    zoom_levels = sorted([int(z.name) for z in zoom_dirs])
    
    min_zoom = min(zoom_levels)
    max_zoom = max(zoom_levels)
    
    print(f"Zoom levels found: {min_zoom} - {max_zoom}")

    # Insert minimal metadata up front; bounds/center are derived from the
    # actual tile coverage at the highest zoom and rewritten at the end of
    # the run (the placeholders here exist only so tileserver-gl can open the
    # file mid-conversion if someone is impatient).
    metadata = {
        'name': name,
        'description': description,
        'version': '1.0',
        'type': 'baselayer',
        'format': 'png',
        'minzoom': str(min_zoom),
        'maxzoom': str(max_zoom),
        'bounds': '-180,-85.0511,180,85.0511',  # rewritten below from actual tile extent
        'center': '0,0,0',                       # rewritten below from bounds
        'attribution': 'DeepGIS Rock Tiles'
    }

    for key, value in metadata.items():
        cursor.execute("INSERT OR REPLACE INTO metadata (name, value) VALUES (?, ?)",
                      (key, value))

    conn.commit()

    # Track the (x, y_tms) extent at the deepest zoom so we can compute true
    # bounds/center after the walk. Per-zoom because tile coords are zoom-
    # specific; we use max_zoom for tightest precision.
    extent_at_max = {'xmin': None, 'xmax': None, 'ymin': None, 'ymax': None}

    # Import tiles
    print(f"\nConverting tiles...")
    total_tiles = 0

    for zoom in zoom_levels:
        zoom_path = tiles_path / str(zoom)
        if not zoom_path.exists():
            continue

        print(f"Processing zoom level {zoom}...", end=' ', flush=True)
        zoom_tile_count = 0

        for x_dir in zoom_path.iterdir():
            if not x_dir.is_dir():
                continue

            x = int(x_dir.name)

            for tile_file in x_dir.glob('*.png'):
                y = int(tile_file.stem)

                # The raw pyramid generated by gdal2tiles uses TMS y by
                # default (Profile=mercator without --xyz). MBTiles also
                # stores tile_row in TMS y. So tile_row = y as-is; do NOT
                # apply (2^zoom - 1 - y) here. (An earlier version of this
                # script applied that flip and the resulting MBTiles served
                # tiles 75 degrees too far south through tileserver-gl,
                # which un-flips on read.) If the source pyramid is XYZ
                # (e.g. produced with `gdal2tiles --xyz`), invert before
                # calling this script or pass --source-convention=xyz.
                tile_row = y

                # Read tile data
                try:
                    with open(tile_file, 'rb') as f:
                        tile_data = f.read()

                    # Insert into database
                    cursor.execute("""
                        INSERT OR REPLACE INTO tiles
                        (zoom_level, tile_column, tile_row, tile_data)
                        VALUES (?, ?, ?, ?)
                    """, (zoom, x, tile_row, tile_data))

                    total_tiles += 1
                    zoom_tile_count += 1

                    if zoom == max_zoom:
                        if extent_at_max['xmin'] is None or x < extent_at_max['xmin']:
                            extent_at_max['xmin'] = x
                        if extent_at_max['xmax'] is None or x > extent_at_max['xmax']:
                            extent_at_max['xmax'] = x
                        if extent_at_max['ymin'] is None or tile_row < extent_at_max['ymin']:
                            extent_at_max['ymin'] = tile_row
                        if extent_at_max['ymax'] is None or tile_row > extent_at_max['ymax']:
                            extent_at_max['ymax'] = tile_row

                    # Commit every 1000 tiles for progress
                    if total_tiles % 1000 == 0:
                        conn.commit()
                        print(f"\r  Processed {total_tiles} tiles...", end='', flush=True)

                except Exception as e:
                    print(f"\nWarning: Could not process {tile_file}: {e}")
                    continue

        print(f" {zoom_tile_count} tiles")

    # Derive true bounds/center from the deepest zoom we just ingested.
    # tile_row in MBTiles is TMS y; convert to XYZ y to get lat. Standard
    # slippy-map formulas.
    if extent_at_max['xmin'] is not None:
        import math
        n = 1 << max_zoom
        xmin, xmax = extent_at_max['xmin'], extent_at_max['xmax']
        y_tms_min, y_tms_max = extent_at_max['ymin'], extent_at_max['ymax']
        y_xyz_top = (n - 1) - y_tms_max  # north (smaller y_xyz)
        y_xyz_bot = (n - 1) - y_tms_min  # south
        west  = (xmin       / n) * 360.0 - 180.0
        east  = ((xmax + 1) / n) * 360.0 - 180.0
        north = math.degrees(math.atan(math.sinh(math.pi * (1 - 2.0 *  y_xyz_top      / n))))
        south = math.degrees(math.atan(math.sinh(math.pi * (1 - 2.0 * (y_xyz_bot + 1) / n))))
        bounds_str = f"{west:.6f},{south:.6f},{east:.6f},{north:.6f}"
        center_str = f"{(west+east)/2:.6f},{(south+north)/2:.6f},{max(min_zoom, max_zoom - 3)}"
        cursor.execute("UPDATE metadata SET value=? WHERE name='bounds'", (bounds_str,))
        cursor.execute("UPDATE metadata SET value=? WHERE name='center'", (center_str,))
        print(f"\nDerived bounds: {bounds_str}")
        print(f"Derived center: {center_str}")
    
    # Final commit and optimize
    print("\nOptimizing database...")
    conn.commit()
    cursor.execute("CREATE INDEX IF NOT EXISTS tiles_idx ON tiles (zoom_level, tile_column, tile_row)")
    cursor.execute("ANALYZE")
    conn.commit()
    conn.close()
    
    file_size_mb = os.path.getsize(output_file) / (1024**2)
    
    print(f"\n✅ Conversion complete!")
    print(f"   Total tiles: {total_tiles:,}")
    print(f"   Zoom range: {min_zoom} - {max_zoom}")
    print(f"   Output file: {output_file}")
    print(f"   File size: {file_size_mb:.1f} MB")
    print(f"\nNext steps:")
    print(f"   1. Move to tileserver: cp {output_file} /home/jdas/dreams-lab-website-server/deepgis-xr/data/")
    print(f"   2. Restart tileserver: docker restart deepgis-xr_tileserver_1")
    print(f"   3. View at: https://mbtiles.deepgis.org/")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Convert XYZ tiles to MBTiles')
    parser.add_argument('--tiles_dir', type=str, required=True,
                       help='Directory containing XYZ tiles (with zoom/x/y.png structure)')
    parser.add_argument('--output', type=str, required=True,
                       help='Output .mbtiles file path')
    parser.add_argument('--name', type=str, default='Rock Tiles',
                       help='Layer name (shown in TileServer)')
    parser.add_argument('--description', type=str, default='DeepGIS Rock Imagery',
                       help='Layer description')
    
    args = parser.parse_args()
    
    # Validate inputs
    tiles_dir = Path(args.tiles_dir)
    if not tiles_dir.exists():
        print(f"Error: Tiles directory not found: {tiles_dir}")
        exit(1)
    
    output_file = Path(args.output)
    if output_file.exists():
        response = input(f"Output file {output_file} exists. Overwrite? (y/n): ")
        if response.lower() != 'y':
            print("Aborted.")
            exit(0)
    
    create_mbtiles(
        str(tiles_dir),
        str(output_file),
        args.name,
        args.description
    )
