# Generated by Django 3.2.13 on 2023-12-09 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_laboratory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('stop_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('affiliation', models.CharField(max_length=200)),
            ],
        ),
    ]
