# Generated by Django 3.2.25 on 2025-01-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='email',
            field=models.EmailField(default='none@none.null', help_text='Preferably your ASU email', max_length=254),
            preserve_default=False,
        ),
    ]
