# Generated by Django 3.2.13 on 2023-12-09 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_laboratory', '0002_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dreams_laboratory.role'),
        ),
    ]
