# Generated by Django 3.2.25 on 2025-11-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_laboratory', '0002_quizsubmission_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneTelemetrySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=100, unique=True)),
                ('start_time', models.DateTimeField(help_text='Session start timestamp')),
                ('end_time', models.DateTimeField(blank=True, help_text='Session end timestamp', null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Session duration in seconds', null=True)),
                ('flight_mode', models.CharField(blank=True, help_text='PX4 flight mode (e.g., MANUAL, POSCTL, AUTO)', max_length=50, null=True)),
                ('mission_type', models.CharField(blank=True, help_text='Type of mission/flight', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional session notes', null=True)),
                ('total_telemetry_points', models.PositiveIntegerField(default=0, help_text='Total number of telemetry records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='Drone asset this telemetry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_sessions', to='dreams_laboratory.asset')),
                ('project', models.ForeignKey(blank=True, help_text='Associated project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_sessions', to='dreams_laboratory.project')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='LocalPositionOdom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='PX4 timestamp (microseconds since boot)')),
                ('timestamp_usec', models.BigIntegerField(help_text='Microseconds since system boot')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When record was received by server')),
                ('x', models.FloatField(help_text='North position (m)')),
                ('y', models.FloatField(help_text='East position (m)')),
                ('z', models.FloatField(help_text='Down position (m, positive down)')),
                ('vx', models.FloatField(blank=True, help_text='North velocity (m/s)', null=True)),
                ('vy', models.FloatField(blank=True, help_text='East velocity (m/s)', null=True)),
                ('vz', models.FloatField(blank=True, help_text='Down velocity (m/s)', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Heading angle (rad, 0 = North)', null=True)),
                ('heading_rate', models.FloatField(blank=True, help_text='Heading rate (rad/s)', null=True)),
                ('position_covariance', models.JSONField(blank=True, default=list, help_text='Position covariance matrix (9 elements)')),
                ('velocity_covariance', models.JSONField(blank=True, default=list, help_text='Velocity covariance matrix (9 elements)')),
                ('xy_valid', models.BooleanField(default=False, help_text='XY position valid')),
                ('z_valid', models.BooleanField(default=False, help_text='Z position valid')),
                ('v_xy_valid', models.BooleanField(default=False, help_text='XY velocity valid')),
                ('v_z_valid', models.BooleanField(default=False, help_text='Z velocity valid')),
                ('heading_valid', models.BooleanField(default=False, help_text='Heading valid')),
                ('ref_timestamp', models.BigIntegerField(blank=True, help_text='Reference timestamp for local frame', null=True)),
                ('ref_lat', models.FloatField(blank=True, help_text='Reference latitude (deg) for local frame origin', null=True)),
                ('ref_lon', models.FloatField(blank=True, help_text='Reference longitude (deg) for local frame origin', null=True)),
                ('ref_alt', models.FloatField(blank=True, help_text='Reference altitude (m) for local frame origin', null=True)),
                ('dist_bottom', models.FloatField(blank=True, help_text='Distance to bottom surface (m)', null=True)),
                ('dist_bottom_valid', models.BooleanField(default=False, help_text='Distance to bottom valid')),
                ('dist_bottom_sensor_bitfield', models.IntegerField(blank=True, help_text='Sensors used for bottom distance', null=True)),
                ('eph', models.FloatField(blank=True, help_text='Estimated horizontal position error (m)', null=True)),
                ('epv', models.FloatField(blank=True, help_text='Estimated vertical position error (m)', null=True)),
                ('evh', models.FloatField(blank=True, help_text='Estimated horizontal velocity error (m/s)', null=True)),
                ('evv', models.FloatField(blank=True, help_text='Estimated vertical velocity error (m/s)', null=True)),
                ('session', models.ForeignKey(help_text='Telemetry session this data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='local_position_odom', to='dreams_laboratory.dronetelemetrysession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GPSFixRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='GPS timestamp')),
                ('timestamp_usec', models.BigIntegerField(help_text='Microseconds since system boot')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When record was received by server')),
                ('latitude', models.DecimalField(decimal_places=14, help_text='Latitude (deg)', max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=14, help_text='Longitude (deg)', max_digits=17)),
                ('altitude', models.FloatField(help_text='Altitude above MSL (m)')),
                ('fix_type', models.IntegerField(help_text='GPS fix type: 0=no fix, 1=dead reckoning, 2=2D, 3=3D, 4=GPS+DR, 5=Time only')),
                ('satellites_visible', models.PositiveIntegerField(help_text='Number of satellites visible')),
                ('satellites_used', models.PositiveIntegerField(blank=True, help_text='Number of satellites used in solution', null=True)),
                ('hdop', models.FloatField(blank=True, help_text='Horizontal dilution of precision', null=True)),
                ('vdop', models.FloatField(blank=True, help_text='Vertical dilution of precision', null=True)),
                ('pdop', models.FloatField(blank=True, help_text='Position dilution of precision', null=True)),
                ('eph', models.FloatField(blank=True, help_text='GPS horizontal position accuracy (m)', null=True)),
                ('epv', models.FloatField(blank=True, help_text='GPS vertical position accuracy (m)', null=True)),
                ('s_variance_m_s', models.FloatField(blank=True, help_text='GPS speed accuracy (m/s)', null=True)),
                ('vel_n_m_s', models.FloatField(blank=True, help_text='North velocity (m/s)', null=True)),
                ('vel_e_m_s', models.FloatField(blank=True, help_text='East velocity (m/s)', null=True)),
                ('vel_d_m_s', models.FloatField(blank=True, help_text='Down velocity (m/s)', null=True)),
                ('vel_m_s', models.FloatField(blank=True, help_text='Ground speed (m/s)', null=True)),
                ('cog_rad', models.FloatField(blank=True, help_text='Course over ground (rad)', null=True)),
                ('time_utc_usec', models.BigIntegerField(blank=True, help_text='UTC timestamp (microseconds)', null=True)),
                ('noise_per_ms', models.IntegerField(blank=True, help_text='Noise level per millisecond', null=True)),
                ('jamming_indicator', models.IntegerField(blank=True, help_text='Jamming indicator (0-100)', null=True)),
                ('jamming_state', models.IntegerField(blank=True, help_text='Jamming state: 0=unknown, 1=ok, 2=warning, 3=critical', null=True)),
                ('device_id', models.IntegerField(blank=True, help_text='GPS device ID', null=True)),
                ('session', models.ForeignKey(help_text='Telemetry session this data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='gps_fixes_raw', to='dreams_laboratory.dronetelemetrysession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GPSFixEstimated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Estimate timestamp')),
                ('timestamp_usec', models.BigIntegerField(help_text='Microseconds since system boot')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When record was received by server')),
                ('latitude', models.DecimalField(decimal_places=14, help_text='Estimated latitude (deg)', max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=14, help_text='Estimated longitude (deg)', max_digits=17)),
                ('altitude', models.FloatField(help_text='Estimated altitude above MSL (m)')),
                ('position_covariance', models.JSONField(blank=True, default=list, help_text='Position covariance matrix (9 elements)')),
                ('vel_n_m_s', models.FloatField(blank=True, help_text='Estimated North velocity (m/s)', null=True)),
                ('vel_e_m_s', models.FloatField(blank=True, help_text='Estimated East velocity (m/s)', null=True)),
                ('vel_d_m_s', models.FloatField(blank=True, help_text='Estimated Down velocity (m/s)', null=True)),
                ('velocity_covariance', models.JSONField(blank=True, default=list, help_text='Velocity covariance matrix (9 elements)')),
                ('eph', models.FloatField(blank=True, help_text='Estimated horizontal position error (m)', null=True)),
                ('epv', models.FloatField(blank=True, help_text='Estimated vertical position error (m)', null=True)),
                ('evh', models.FloatField(blank=True, help_text='Estimated horizontal velocity error (m/s)', null=True)),
                ('evv', models.FloatField(blank=True, help_text='Estimated vertical velocity error (m/s)', null=True)),
                ('estimator_type', models.CharField(blank=True, help_text='State estimator type (e.g., EKF2, LPE)', max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, help_text='Estimation confidence (0-1)', null=True)),
                ('position_valid', models.BooleanField(default=False, help_text='Estimated position valid')),
                ('velocity_valid', models.BooleanField(default=False, help_text='Estimated velocity valid')),
                ('local_position', models.ForeignKey(blank=True, help_text='Corresponding local position odometry (if available)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimated_gps_fixes', to='dreams_laboratory.localpositionodom')),
                ('raw_gps_fix', models.ForeignKey(blank=True, help_text='Corresponding raw GPS fix (if available)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimated_fixes', to='dreams_laboratory.gpsfixraw')),
                ('session', models.ForeignKey(help_text='Telemetry session this data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='gps_fixes_estimated', to='dreams_laboratory.dronetelemetrysession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='localpositionodom',
            index=models.Index(fields=['session', '-timestamp'], name='dreams_labo_session_981b13_idx'),
        ),
        migrations.AddIndex(
            model_name='localpositionodom',
            index=models.Index(fields=['timestamp'], name='dreams_labo_timesta_57cd80_idx'),
        ),
        migrations.AddIndex(
            model_name='localpositionodom',
            index=models.Index(fields=['timestamp_usec'], name='dreams_labo_timesta_e1b9db_idx'),
        ),
        migrations.AddIndex(
            model_name='localpositionodom',
            index=models.Index(fields=['session', 'timestamp'], name='dreams_labo_session_e122dd_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsfixraw',
            index=models.Index(fields=['session', '-timestamp'], name='dreams_labo_session_563d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsfixraw',
            index=models.Index(fields=['timestamp'], name='dreams_labo_timesta_3315f0_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsfixraw',
            index=models.Index(fields=['latitude', 'longitude'], name='dreams_labo_latitud_7dbbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsfixraw',
            index=models.Index(fields=['fix_type'], name='dreams_labo_fix_typ_5805ad_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsfixraw',
            index=models.Index(fields=['session', 'timestamp'], name='dreams_labo_session_bb2a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsfixestimated',
            index=models.Index(fields=['session', '-timestamp'], name='dreams_labo_session_113bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsfixestimated',
            index=models.Index(fields=['timestamp'], name='dreams_labo_timesta_cc8fee_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsfixestimated',
            index=models.Index(fields=['latitude', 'longitude'], name='dreams_labo_latitud_f17ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsfixestimated',
            index=models.Index(fields=['session', 'timestamp'], name='dreams_labo_session_c5d3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='dronetelemetrysession',
            index=models.Index(fields=['asset', '-start_time'], name='dreams_labo_asset_i_662204_idx'),
        ),
        migrations.AddIndex(
            model_name='dronetelemetrysession',
            index=models.Index(fields=['session_id'], name='dreams_labo_session_33ccc0_idx'),
        ),
        migrations.AddIndex(
            model_name='dronetelemetrysession',
            index=models.Index(fields=['start_time'], name='dreams_labo_start_t_9d5419_idx'),
        ),
    ]
