# Generated by Django 3.2.25 on 2025-11-26 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_laboratory', '0003_auto_20251123_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=255, unique=True)),
                ('num_points', models.IntegerField(default=1000)),
                ('initialization_method', models.CharField(choices=[('uniform', 'Uniform Distribution'), ('gaussian_mixture', 'Gaussian Mixture'), ('population_weighted', 'Population Weighted')], default='uniform', max_length=50)),
                ('lat_range_min', models.FloatField(default=-90)),
                ('lat_range_max', models.FloatField(default=90)),
                ('lon_range_min', models.FloatField(default=-180)),
                ('lon_range_max', models.FloatField(default=180)),
                ('alt_range_min', models.FloatField(default=0)),
                ('alt_range_max', models.FloatField(default=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_samples', models.IntegerField(default=0)),
                ('total_updates', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, help_text='User who created the session', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sampling_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampledLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude in degrees [-90, 90]')),
                ('longitude', models.FloatField(help_text='Longitude in degrees [-180, 180]')),
                ('altitude', models.FloatField(help_text='Altitude in meters')),
                ('zoom_level', models.IntegerField(help_text='Cesium zoom level (0-28)')),
                ('score', models.FloatField(default=0.0, help_text='User feedback score (positive = interesting, negative = avoid)')),
                ('weight', models.FloatField(default=1.0, help_text='Sampling weight/probability at time of sampling')),
                ('session_id', models.CharField(default='default', help_text='Session identifier for grouping samples', max_length=255)),
                ('sampled_at', models.DateTimeField(auto_now_add=True, help_text='When this location was sampled')),
                ('scored_at', models.DateTimeField(blank=True, help_text='When user provided feedback', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (camera params, terrain info, etc.)')),
                ('user', models.ForeignKey(blank=True, help_text='User who provided feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sampled_locations',
                'ordering': ['-sampled_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_rule', models.CharField(choices=[('reward', 'Reward'), ('exploration', 'Exploration'), ('concentration', 'Concentration'), ('custom', 'Custom')], help_text='Update rule applied', max_length=50)),
                ('learning_rate', models.FloatField(help_text='Learning rate used')),
                ('radius', models.FloatField(blank=True, help_text='Influence radius in meters', null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(default=dict, help_text='Additional update parameters')),
                ('feedback_locations', models.ManyToManyField(blank=True, help_text='Locations whose feedback triggered this update', related_name='caused_updates', to='dreams_laboratory.SampledLocation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='dreams_laboratory.samplingsession')),
            ],
            options={
                'db_table': 'distribution_updates',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sampledlocation',
            index=models.Index(fields=['latitude', 'longitude'], name='sampled_loc_latitud_60dc68_idx'),
        ),
        migrations.AddIndex(
            model_name='sampledlocation',
            index=models.Index(fields=['session_id', 'sampled_at'], name='sampled_loc_session_24947d_idx'),
        ),
        migrations.AddIndex(
            model_name='sampledlocation',
            index=models.Index(fields=['score'], name='sampled_loc_score_30031e_idx'),
        ),
        migrations.AddIndex(
            model_name='sampledlocation',
            index=models.Index(fields=['-sampled_at'], name='sampled_loc_sampled_e840ea_idx'),
        ),
    ]
