# Generated by Django 3.2.13 on 2023-12-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_laboratory', '0003_people_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Untitled Project', max_length=200),
        ),
    ]
