# Generated by Django 3.2.13 on 2023-12-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_laboratory', '0008_auto_20231209_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='style',
            field=models.CharField(default="'background-color: rgba(255,0,0,0.3);'", max_length=200),
        ),
    ]
