# Generated by Django 3.2.13 on 2023-12-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_laboratory', '0009_research_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='people',
            name='affiliation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
