# Generated by Django 3.2.13 on 2023-12-10 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_laboratory', '0011_research_effort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='dreams_laboratory.people')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='dreams_laboratory.photo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='dreams_laboratory.project')),
            ],
        ),
    ]
