# Generated by Django 3.2.13 on 2023-12-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_laboratory', '0012_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
