# Generated by Django 3.2.13 on 2023-12-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_laboratory', '0013_auto_20231210_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='project',
        ),
        migrations.AddField(
            model_name='photo',
            name='assets',
            field=models.ManyToManyField(blank=True, to='dreams_laboratory.Asset'),
        ),
        migrations.AddField(
            model_name='photo',
            name='projects',
            field=models.ManyToManyField(blank=True, to='dreams_laboratory.Project'),
        ),
        migrations.AddField(
            model_name='photo',
            name='researches',
            field=models.ManyToManyField(blank=True, to='dreams_laboratory.Research'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_url',
            field=models.URLField(max_length=300),
        ),
    ]
