# Generated by Django 3.2.13 on 2023-12-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_laboratory', '0015_auto_20231210_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='profile_pic',
            field=models.URLField(max_length=300),
        ),
    ]
