# Generated by Django 3.2.13 on 2023-12-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_laboratory', '0016_alter_people_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='photo_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
