# Generated by Django 3.2.13 on 2023-12-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_laboratory', '0017_fundingsource_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
