# Generated by Django 3.2.25 on 2024-12-27 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=64, unique=True)),
                ('unique_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ports', models.JSONField(default=dict)),
                ('image', models.CharField(max_length=100)),
                ('session_type', models.CharField(default='guest', max_length=20)),
                ('subdomain', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('container_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('network', models.CharField(default='openuav_network', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['subdomain'], name='openuav_man_subdoma_ef6c82_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['container_ip'], name='openuav_man_contain_89b1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['status'], name='openuav_man_status_c00d33_idx'),
        ),
    ]
