# Generated by Django 3.2.25 on 2024-12-25 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openuav_manager', '0001_create_container_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='container',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='container',
            name='session_type',
            field=models.CharField(choices=[('guest', 'Guest Session'), ('user', 'User Session')], default='guest', max_length=10),
        ),
        migrations.AddField(
            model_name='container',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['session_type', 'status'], name='openuav_man_session_632dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['user', 'status'], name='openuav_man_user_id_569bb7_idx'),
        ),
    ]
