# Generated by Django 3.2.25 on 2024-12-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openuav_manager', '0003_auto_20241230_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='container',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='container',
            name='session_type',
            field=models.CharField(choices=[('guest', 'Guest Session'), ('user', 'User Session')], default='guest', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
