# Generated by Django 3.2.25 on 2024-12-30 08:00

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('openuav_manager', '0004_auto_20241230_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ] 