# Generated by Django 3.2.25 on 2024-12-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openuav_manager', '0005_add_last_accessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='vnc_url',
            field=models.URLField(blank=True, help_text='URL for VNC access', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='ports',
            field=models.JSONField(default=dict, help_text='Mapping of host ports to container ports'),
        ),
    ]
