# Generated by Django 3.2.25 on 2024-12-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openuav_manager', '0006_auto_20241231_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['session_id', 'status'], name='openuav_man_session_80cb20_idx'),
        ),
    ]
