# Generated by Django 3.2.25 on 2025-01-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openuav_manager', '0007_auto_20241231_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='container',
            name='short_id',
            field=models.CharField(default='none', help_text='Short container ID (first 12 characters)', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='container_id',
            field=models.CharField(help_text='Full container ID', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['short_id'], name='openuav_man_short_i_3a693a_idx'),
        ),
    ]
