# Generated by Django 3.2.25 on 2025-11-07 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openuav_manager', '0008_auto_20250101_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosbagFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('topics', models.JSONField(default=list, help_text='List of topics with message counts')),
                ('metadata', models.JSONField(default=dict, help_text='Full metadata.yaml contents')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('indexed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-indexed'],
            },
        ),
        migrations.CreateModel(
            name='RosbagSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualization_type', models.CharField(choices=[('rviz2', 'RViz2'), ('foxglove', 'Foxglove Studio'), ('plotjuggler', 'PlotJuggler'), ('rqt_bag', 'rqt_bag')], default='rviz2', max_length=50)),
                ('playback_rate', models.FloatField(default=1.0, help_text='Playback rate multiplier')),
                ('is_looping', models.BooleanField(default=False)),
                ('is_playing', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosbag_sessions', to='openuav_manager.container')),
                ('rosbag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='openuav_manager.rosbagfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rosbag_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='rosbagfile',
            index=models.Index(fields=['name'], name='openuav_man_name_94d6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='rosbagfile',
            index=models.Index(fields=['indexed'], name='openuav_man_indexed_5aad3c_idx'),
        ),
        migrations.AddIndex(
            model_name='rosbagsession',
            index=models.Index(fields=['user', 'created'], name='openuav_man_user_id_e4348f_idx'),
        ),
        migrations.AddIndex(
            model_name='rosbagsession',
            index=models.Index(fields=['container', 'is_playing'], name='openuav_man_contain_a94c0e_idx'),
        ),
    ]
